import { describe, expect, it } from 'vitest';
import type { Id, RequestContext, ToolAdapter, ToolManifest } from '@uniforge/contracts';
import { ToolGatewayService, createInternalReadTool, createMcpTool, createLocalFileReadTool, createGitReadTool, createHttpTool } from './index.js';

const ctx: RequestContext = { actorId: 'actor_main' as Id<'actor'>, workspaceId: 'workspace_main' as Id<'workspace'>, correlationId: 'tool-test' };
const manifest = (overrides: Partial<ToolManifest> = {}): ToolManifest => ({ id: 'test.read', version: '1.0.0', source: 'internal', capabilities: ['workspace.read'], inputSchema: { type: 'object', required: ['value'], properties: { value: { type: 'string' } } }, outputSchema: { type: 'string' }, filesystemScope: [], networkScope: [], credentialScope: [], riskLevel: 'LOW', approvalPolicy: 'never', timeoutMs: 100, resourceLimit: {}, license: 'UniForge' , ...overrides });
const adapter = (m = manifest(), fn: ToolAdapter['execute'] = async (input) => ({ ok: true, value: input })) => ({ manifest: m, execute: fn });
const allowed = { check: () => ({ decision: 'ALLOW' as const, reason: 'test' }) };

describe('ToolGatewayService', () => {
  it('validates schema and records provenance', async () => { const g = new ToolGatewayService(allowed); const m = manifest({ outputSchema: { type: 'object' } }); g.register(adapter(m)); expect((await g.invoke('test.read', { value: 'ok' }, ctx))).toMatchObject({ ok: true, value: { output: { value: 'ok' }, provenance: { toolId: 'test.read', source: 'internal', correlationId: 'tool-test' } } }); expect((await g.invoke('test.read', { value: 1 }, ctx))).toMatchObject({ ok: false, error: { code: 'INVALID_INPUT' } }); });
  it('enforces approval, timeout, cancellation and exposes failures', async () => { const high = manifest({ id: 'danger', riskLevel: 'HIGH', approvalPolicy: 'on-risk' }); const permission = { ...allowed, verifyApproval: () => true }; const g = new ToolGatewayService(permission); g.register(adapter(high, async () => { await new Promise((r) => setTimeout(r, 200)); return { ok: true, value: 'x' }; })); expect(await g.invoke('danger', { value: 'x' }, ctx)).toMatchObject({ ok: false, error: { code: 'APPROVAL_REQUIRED' } }); const controller = new AbortController(); controller.abort(); expect(await g.invoke('danger', { value: 'x' }, ctx, { approvalToken: 'approved', signal: controller.signal })).toMatchObject({ ok: false, error: { code: 'CANCELLED' } }); });
  it('supports local, git, http and MCP adapters', async () => { const g = new ToolGatewayService(allowed); g.register(createInternalReadTool('internal.read', async () => ({ answer: 42 }))); g.register(createLocalFileReadTool('local.file', 'C:\\tmp')); g.register(createGitReadTool('git.status', async () => 'clean')); g.register(createHttpTool('http.get', async () => new Response('{"ok":true}'))); g.register(createMcpTool('mcp.echo', { call: async () => ({ content: [{ type: 'text', text: 'pong' }] }) })); expect((await g.invoke('internal.read', {}, ctx)).ok).toBe(true); expect((await g.invoke('git.status', {}, ctx)).ok).toBe(true); expect((await g.invoke('http.get', { url: 'https://example.test' }, ctx)).ok).toBe(true); expect((await g.invoke('mcp.echo', {}, ctx)).ok).toBe(true); });
  it('keeps MCP disconnects and malformed responses visible', async () => { const g = new ToolGatewayService(allowed); g.register(createMcpTool('mcp.bad', { call: async () => ({ nope: true }) })); g.register(createMcpTool('mcp.down', { call: async () => { throw new Error('disconnected'); } })); expect(await g.invoke('mcp.bad', {}, ctx)).toMatchObject({ ok: false, error: { code: 'CONFLICT', correlationId: 'tool-test' } }); expect(await g.invoke('mcp.down', {}, ctx)).toMatchObject({ ok: false, error: { code: 'UNAVAILABLE', message: 'disconnected' } }); });
});
