export type Brand<T, B extends string> = T & { readonly __brand: B };
export type CoreBoundary = 'domain' | 'application';
export * from './domain/primitives.js';
export * from './domain/entities.js';
export * from './domain/commands.js';
export * from './domain/events.js';
export * from './domain/permission.js';
export * from './domain/memory.js';
export * from './model/gateway.js';
export * from './tool/gateway.js';
export * from './agent/definition.js';
export * from './agent/runtime.js';
export * from './agent/center.js';
export * from './app-shell/navigation.js';
export * from './settings/index.js';
export * from './dashboard/index.js';
export * from './course/index.js';
export * from './voice/index.js';
export * from './lifecycle/index.js';

export * from './english/exam-space.js';
export * from './english/vocabulary.js';
export * from './english/learning-dimensions.js';
export * from './english/training.js';
export * from './english/ielts.js';
export * from './english/mock-exam.js';
export * from './knowledge/content.js';
export * from './knowledge/topic.js';
export * from './knowledge/extraction.js';
export * from './knowledge/search.js';
export * from './knowledge/decision.js';
